- https://personal.math.ubc.ca/~pwalls/math-python/linear-algebra/linear-algebra-scipy/

In [3]:
import numpy as np 
import scipy.linalg as la 

Create a 1D Numpy array and verify its dimensions, shape ans size.

In [2]:
a = np.array([1, 3, -2, 1])
print(a)

[ 1  3 -2  1]


In [3]:
# Verify the number of dimensions:
a.ndim 

1

In [4]:
# verify the shape of the array:
a.shape 

(4,)

In [5]:
a.size 

4

Create a 2D Numpy array(ie. matrix)

In [6]:
M = np.array([[1,2], [3,7], [-1,5]])
print(M)

[[ 1  2]
 [ 3  7]
 [-1  5]]


In [7]:
# Verify the number of dimensions:
M.ndim 

2

In [8]:
# Verify the shape of the array:
M.shape 

(3, 2)

In [9]:
# Finally, verify the total number of entries in the array:
M.size

6

In [11]:
# Select a row or column form a 2D array and we get a 1D array:
col = M[:,1]
print(col)

[2 7 5]


When we select a row of column form a 2D array, the result is a 1D array. However, we may want to select a column as a 2D column vector. This requires us to use the `reshape` method.    
For example, create a 2D column vector form the 1D slice selected from the matrix `M` above:

In [13]:
print(col)
print('-'*10)
column = col.reshape(3,1)
print(column)

[2 7 5]
----------
[[2]
 [7]
 [5]]


In [14]:
# verify the dimensions, shape and size of the array:
print(f'Dimensions: {column.ndim}')
print(f'shape: {column.shape}')
print(f'size: {column.size}')

Dimensions: 2
shape: (3, 1)
size: 3


## Matrix Operations and Functions
### Arithmetic Operations 
recall that arithmetic array operations `+, -, /, *, **` are performed elementwise on Numpy arrays.    
Let's create a numpy array and do some computations:

In [15]:
M = np.array([[3, 4], [-1, 5]])
print(M)

[[ 3  4]
 [-1  5]]


In [17]:
M * M

array([[ 9, 16],
       [ 1, 25]])

### Matrix Multiplication 
We use the `@` operator to do matrix multiplication with numpy arrays:

In [18]:
M @ M

array([[ 5, 32],
       [-8, 21]])

Let's compute 2I + 3A - AB for    
   
> $A = \begin{bmatrix} 1 & 3 \\ -1 & 7 \end{bmatrix} \qquad B = \begin{bmatrix} 5 & 2 \\ 1 & 2 \end{bmatrix}$  
   
and I is the identity matrix of size 2:

In [19]:
A = np.array([[1, 3], [-1, 7]])
print(A)
print('-'*10)
B = np.array([[5, 2], [1, 2]])
print(B)

[[ 1  3]
 [-1  7]]
----------
[[5 2]
 [1 2]]


In [20]:
I = np.eye(2)
print(I)

[[1. 0.]
 [0. 1.]]


In [21]:
2*I + 3*A - A@B 

array([[-3.,  1.],
       [-5., 11.]])

### Matrix Powers(형렬의 거듭제곱)
There's no symbol for matrix powers and so we must import the function `matrix_power` from the subpackage `numpy.linalg`.

In [22]:
from numpy.linalg import matrix_power as mpow 

In [23]:
M = np.array([[3, 4], [-1, 5]])
print(M)

[[ 3  4]
 [-1  5]]


In [24]:
mpow(M, 2)

array([[ 5, 32],
       [-8, 21]])

In [25]:
M @ M 

array([[ 5, 32],
       [-8, 21]])

### Tranpose 
We can take the transpose with `.T` attribute:

In [26]:
print(M)
print('-'*10)
print(M.T)

[[ 3  4]
 [-1  5]]
----------
[[ 3 -1]
 [ 4  5]]


In [27]:
# Notice that MM^T is a symmetric matrix:
M @ M.T 

array([[25, 17],
       [17, 26]])

### Inverse 
We can find the inverse using the function `scipy.linalg.inv`:

In [31]:
A = np.array([[1, 2], [3, 4]])
print(A)

[[1 2]
 [3 4]]


In [32]:
la.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [33]:
A @ la.inv(A)

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

### Trace 
We can find the trace of a matrix using the function `numpy.trace`:

In [34]:
np.trace(A)

5

## Norm 
### Determinant
We find the determinant using the function `scipy.linalg.det`:

In [35]:
A = np.array([[1, 2], [3, 4]])
print(A)
print('-'*10)
la.det(A)

[[1 2]
 [3 4]]
----------


-2.0

## Dot Product
### Characteristic Polynomials and Cayley-Hamilton Theorem
The characteristic polynomial of a 2 by 2 square matrix A is   
   
> $ p_{A}(\lambda) = det(A - \lambda I) = \lambda^2 - tr(A)\lambda + det(A) $     
   
The Cayley-Hamilton Theorem states that any square matrix satisfies its characteristic polynomial. For a matrix A of size 2, this means that    
   
> $ p_{A} = A^2 - tr(A)A + det(A)I = 0 $   
   
Let's verify the Cayley-Hamilton Theorem for a few different matrices.

In [36]:
print(A)

[[1 2]
 [3 4]]


In [37]:
trace_A = np.trace(A)
det_A = la.det(A)
I = np.eye(2)

A @ A - trace_A * A + det_A * I 

array([[0., 0.],
       [0., 0.]])

In [41]:
# Let's do this again for some random matrices:
N = np.random.randint(0, 10, [2,2])
print(N)

[[1 9]
 [6 9]]


In [42]:
trance_N = np.trace(N)
det_N = la.det(N)
I = np.eye(2)

N @ N - trance_N * N + det_N * I 

array([[0., 0.],
       [0., 0.]])

### Projections
The formula to project a vector $v$ onto a vector $w$ is  
  
$ proj_w(v) = { vw \over ww }w $   

Let's a function called `proj` which computes the projection $v$ onto $w$.      

In [6]:
def proj(v, w):
  # Project vector v onto w
  _v = np.array(v)
  _w = np.array(w)
  return np.sum(_v * _w) / np.sum(_w * _w) * _w # (_v @ _w) / (_w @ _w) * _w

In [7]:
proj([1,2,3],[1,1,1])

array([2., 2., 2.])