- https://pandas.pydata.org/docs/user_guide/io.html

In [7]:
import pandas as pd
import numpy as np

# Creating
### Series

In [6]:
s1 = pd.Series([1, 2, 3, 4, 5, 6])
s2 = pd.Series([1, 2.2, 3, 4.5, 6, 7], index=['a', 'b', 'c', 'd', 'e', 'f'])
s1, s2

(0    1
 1    2
 2    3
 3    4
 4    5
 5    6
 dtype: int64,
 a    1.0
 b    2.2
 c    3.0
 d    4.5
 e    6.0
 f    7.0
 dtype: float64)

### DataFrame

In [9]:
df_idx = pd.date_range('20130101', periods=6)
df_values = np.random.randn(6, 4)
df_columns = list('ABCD')
df = pd.DataFrame(df_values, index=df_idx, columns=df_columns)
print(df_idx)
print('-'*10)
print(df_values)
print('-'*10)
print(df_columns)
print('-'*10)
print(df)

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')
----------
[[-0.75369154  1.13842469  0.37423729  0.14680415]
 [-1.40951249  0.43949237  0.32997301 -1.38318985]
 [-1.11281292  0.60954738 -0.59014959 -1.32065541]
 [ 1.00613874 -0.51462823  0.49840368 -1.49440466]
 [-0.55713322 -0.26256804 -1.03954832  0.17557805]
 [-1.02150737  0.68927084  0.4869062  -0.16979278]]
----------
['A', 'B', 'C', 'D']
----------
                   A         B         C         D
2013-01-01 -0.753692  1.138425  0.374237  0.146804
2013-01-02 -1.409512  0.439492  0.329973 -1.383190
2013-01-03 -1.112813  0.609547 -0.590150 -1.320655
2013-01-04  1.006139 -0.514628  0.498404 -1.494405
2013-01-05 -0.557133 -0.262568 -1.039548  0.175578
2013-01-06 -1.021507  0.689271  0.486906 -0.169793


> - 날짜 인덱스와 레이블이 지정된 열이 있는 Numpy 어레이를 전달함으로써 DataFrame을 만들 수 있습니다.  
> - date_range() 함수를 사용하여 '20130101'를 시작으로 하는 6개의 DatetimeIndex를 만들었습니다.  
> - 각 날짜마다 A, B, C, D 열에 해당하는 난수 데이터의 DataFrame이 만들어졌습니다.